// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _DeleteDraftEp } from '../src/api/deleteDraft';
import type { default as _GetApplicationEp } from '../src/api/getApplication';
import type { default as _GetMeEp } from '../src/api/getMe';
import type { default as _GetPortalEp } from '../src/api/getPortal';
import type { default as _GetPortalReviewEp } from '../src/api/getPortalReview';
import type { default as _GetPublicProgramEp } from '../src/api/getPublicProgram';
import type { default as _GetTaskEp } from '../src/api/getTask';
import type { default as _ListMyApplicationsEp } from '../src/api/listMyApplications';
import type { default as _ListPortalReviewsEp } from '../src/api/listPortalReviews';
import type { default as _SaveDraftEp } from '../src/api/saveDraft';
import type { default as _SavePortalReviewEp } from '../src/api/savePortalReview';
import type { default as _SaveProfileEp } from '../src/api/saveProfile';
import type { default as _SaveTaskDraftEp } from '../src/api/saveTaskDraft';
import type { default as _SendApplicantMessageEp } from '../src/api/sendApplicantMessage';
import type { default as _StartApplicationEp } from '../src/api/startApplication';
import type { default as _SubmitApplicationEp } from '../src/api/submitApplication';
import type { default as _SubmitTaskEp } from '../src/api/submitTask';
import type { default as _WithdrawApplicationEp } from '../src/api/withdrawApplication';

type _DeleteDraftCfg = typeof _DeleteDraftEp;
export type DeleteDraftInputType = NonNullable<_DeleteDraftCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteDraftCfg['execute']>[0]['input'];
export type DeleteDraftOutputType = Awaited<ReturnType<_DeleteDraftCfg['execute']>>;
export const deleteDraft = createCaller<DeleteDraftInputType, DeleteDraftOutputType>('deleteDraft');

type _GetApplicationCfg = typeof _GetApplicationEp;
export type GetApplicationInputType = NonNullable<_GetApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetApplicationCfg['execute']>[0]['input'];
export type GetApplicationOutputType = Awaited<ReturnType<_GetApplicationCfg['execute']>>;
export const getApplication = createCaller<GetApplicationInputType, GetApplicationOutputType>('getApplication');

type _GetMeCfg = typeof _GetMeEp;
export type GetMeInputType = NonNullable<_GetMeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMeCfg['execute']>[0]['input'];
export type GetMeOutputType = Awaited<ReturnType<_GetMeCfg['execute']>>;
export const getMe = createCaller<GetMeInputType, GetMeOutputType>('getMe');

type _GetPortalCfg = typeof _GetPortalEp;
export type GetPortalInputType = NonNullable<_GetPortalCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPortalCfg['execute']>[0]['input'];
export type GetPortalOutputType = Awaited<ReturnType<_GetPortalCfg['execute']>>;
export const getPortal = createCaller<GetPortalInputType, GetPortalOutputType>('getPortal');

type _GetPortalReviewCfg = typeof _GetPortalReviewEp;
export type GetPortalReviewInputType = NonNullable<_GetPortalReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPortalReviewCfg['execute']>[0]['input'];
export type GetPortalReviewOutputType = Awaited<ReturnType<_GetPortalReviewCfg['execute']>>;
export const getPortalReview = createCaller<GetPortalReviewInputType, GetPortalReviewOutputType>('getPortalReview');

type _GetPublicProgramCfg = typeof _GetPublicProgramEp;
export type GetPublicProgramInputType = NonNullable<_GetPublicProgramCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPublicProgramCfg['execute']>[0]['input'];
export type GetPublicProgramOutputType = Awaited<ReturnType<_GetPublicProgramCfg['execute']>>;
export const getPublicProgram = createCaller<GetPublicProgramInputType, GetPublicProgramOutputType>('getPublicProgram');

type _GetTaskCfg = typeof _GetTaskEp;
export type GetTaskInputType = NonNullable<_GetTaskCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetTaskCfg['execute']>[0]['input'];
export type GetTaskOutputType = Awaited<ReturnType<_GetTaskCfg['execute']>>;
export const getTask = createCaller<GetTaskInputType, GetTaskOutputType>('getTask');

type _ListMyApplicationsCfg = typeof _ListMyApplicationsEp;
export type ListMyApplicationsInputType = NonNullable<_ListMyApplicationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListMyApplicationsCfg['execute']>[0]['input'];
export type ListMyApplicationsOutputType = Awaited<ReturnType<_ListMyApplicationsCfg['execute']>>;
export const listMyApplications = createCaller<ListMyApplicationsInputType, ListMyApplicationsOutputType>('listMyApplications');

type _ListPortalReviewsCfg = typeof _ListPortalReviewsEp;
export type ListPortalReviewsInputType = NonNullable<_ListPortalReviewsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPortalReviewsCfg['execute']>[0]['input'];
export type ListPortalReviewsOutputType = Awaited<ReturnType<_ListPortalReviewsCfg['execute']>>;
export const listPortalReviews = createCaller<ListPortalReviewsInputType, ListPortalReviewsOutputType>('listPortalReviews');

type _SaveDraftCfg = typeof _SaveDraftEp;
export type SaveDraftInputType = NonNullable<_SaveDraftCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveDraftCfg['execute']>[0]['input'];
export type SaveDraftOutputType = Awaited<ReturnType<_SaveDraftCfg['execute']>>;
export const saveDraft = createCaller<SaveDraftInputType, SaveDraftOutputType>('saveDraft');

type _SavePortalReviewCfg = typeof _SavePortalReviewEp;
export type SavePortalReviewInputType = NonNullable<_SavePortalReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SavePortalReviewCfg['execute']>[0]['input'];
export type SavePortalReviewOutputType = Awaited<ReturnType<_SavePortalReviewCfg['execute']>>;
export const savePortalReview = createCaller<SavePortalReviewInputType, SavePortalReviewOutputType>('savePortalReview');

type _SaveProfileCfg = typeof _SaveProfileEp;
export type SaveProfileInputType = NonNullable<_SaveProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveProfileCfg['execute']>[0]['input'];
export type SaveProfileOutputType = Awaited<ReturnType<_SaveProfileCfg['execute']>>;
export const saveProfile = createCaller<SaveProfileInputType, SaveProfileOutputType>('saveProfile');

type _SaveTaskDraftCfg = typeof _SaveTaskDraftEp;
export type SaveTaskDraftInputType = NonNullable<_SaveTaskDraftCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTaskDraftCfg['execute']>[0]['input'];
export type SaveTaskDraftOutputType = Awaited<ReturnType<_SaveTaskDraftCfg['execute']>>;
export const saveTaskDraft = createCaller<SaveTaskDraftInputType, SaveTaskDraftOutputType>('saveTaskDraft');

type _SendApplicantMessageCfg = typeof _SendApplicantMessageEp;
export type SendApplicantMessageInputType = NonNullable<_SendApplicantMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendApplicantMessageCfg['execute']>[0]['input'];
export type SendApplicantMessageOutputType = Awaited<ReturnType<_SendApplicantMessageCfg['execute']>>;
export const sendApplicantMessage = createCaller<SendApplicantMessageInputType, SendApplicantMessageOutputType>('sendApplicantMessage');

type _StartApplicationCfg = typeof _StartApplicationEp;
export type StartApplicationInputType = NonNullable<_StartApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_StartApplicationCfg['execute']>[0]['input'];
export type StartApplicationOutputType = Awaited<ReturnType<_StartApplicationCfg['execute']>>;
export const startApplication = createCaller<StartApplicationInputType, StartApplicationOutputType>('startApplication');

type _SubmitApplicationCfg = typeof _SubmitApplicationEp;
export type SubmitApplicationInputType = NonNullable<_SubmitApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitApplicationCfg['execute']>[0]['input'];
export type SubmitApplicationOutputType = Awaited<ReturnType<_SubmitApplicationCfg['execute']>>;
export const submitApplication = createCaller<SubmitApplicationInputType, SubmitApplicationOutputType>('submitApplication');

type _SubmitTaskCfg = typeof _SubmitTaskEp;
export type SubmitTaskInputType = NonNullable<_SubmitTaskCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitTaskCfg['execute']>[0]['input'];
export type SubmitTaskOutputType = Awaited<ReturnType<_SubmitTaskCfg['execute']>>;
export const submitTask = createCaller<SubmitTaskInputType, SubmitTaskOutputType>('submitTask');

type _WithdrawApplicationCfg = typeof _WithdrawApplicationEp;
export type WithdrawApplicationInputType = NonNullable<_WithdrawApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_WithdrawApplicationCfg['execute']>[0]['input'];
export type WithdrawApplicationOutputType = Awaited<ReturnType<_WithdrawApplicationCfg['execute']>>;
export const withdrawApplication = createCaller<WithdrawApplicationInputType, WithdrawApplicationOutputType>('withdrawApplication');


export const api = {
  deleteDraft,
  getApplication,
  getMe,
  getPortal,
  getPortalReview,
  getPublicProgram,
  getTask,
  listMyApplications,
  listPortalReviews,
  saveDraft,
  savePortalReview,
  saveProfile,
  saveTaskDraft,
  sendApplicantMessage,
  startApplication,
  submitApplication,
  submitTask,
  withdrawApplication,
};
