// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AddNoteEp } from '../src/api/addNote';
import type { default as _AiDraftApplicantFeedbackEp } from '../src/api/aiDraftApplicantFeedback';
import type { default as _AiGenerateFormEp } from '../src/api/aiGenerateForm';
import type { default as _AiSummarizeSubmissionEp } from '../src/api/aiSummarizeSubmission';
import type { default as _AiSynthesizeReviewsEp } from '../src/api/aiSynthesizeReviews';
import type { default as _AssignReviewersEp } from '../src/api/assignReviewers';
import type { default as _BootstrapEp } from '../src/api/bootstrap';
import type { default as _BulkUpdateSubmissionsEp } from '../src/api/bulkUpdateSubmissions';
import type { default as _ClearDemoDataEp } from '../src/api/clearDemoData';
import type { default as _CreateSubmissionEp } from '../src/api/createSubmission';
import type { default as _DecideSubmissionsEp } from '../src/api/decideSubmissions';
import type { default as _DeleteSubmissionsEp } from '../src/api/deleteSubmissions';
import type { default as _ExportSubmissionPdfEp } from '../src/api/exportSubmissionPdf';
import type { default as _ExportSubmissionsEp } from '../src/api/exportSubmissions';
import type { default as _GetApplicantEp } from '../src/api/getApplicant';
import type { default as _GetFormEp } from '../src/api/getForm';
import type { default as _GetProgramOverviewEp } from '../src/api/getProgramOverview';
import type { default as _GetReportsEp } from '../src/api/getReports';
import type { default as _GetReviewEp } from '../src/api/getReview';
import type { default as _GetReviewProgressEp } from '../src/api/getReviewProgress';
import type { default as _GetSubmissionEp } from '../src/api/getSubmission';
import type { default as _ListApplicantsEp } from '../src/api/listApplicants';
import type { default as _ListAwardsEp } from '../src/api/listAwards';
import type { default as _ListLabelsEp } from '../src/api/listLabels';
import type { default as _ListMyReviewsEp } from '../src/api/listMyReviews';
import type { default as _ListNotificationsEp } from '../src/api/listNotifications';
import type { default as _ListPaymentsEp } from '../src/api/listPayments';
import type { default as _ListProgramStatsEp } from '../src/api/listProgramStats';
import type { default as _ListSubmissionsEp } from '../src/api/listSubmissions';
import type { default as _ManageReviewEp } from '../src/api/manageReview';
import type { default as _MarkMessagesReadEp } from '../src/api/markMessagesRead';
import type { default as _SaveApplicantEp } from '../src/api/saveApplicant';
import type { default as _SaveAttachmentEp } from '../src/api/saveAttachment';
import type { default as _SaveFormEp } from '../src/api/saveForm';
import type { default as _SaveLabelEp } from '../src/api/saveLabel';
import type { default as _SaveMemberEp } from '../src/api/saveMember';
import type { default as _SavePaymentEp } from '../src/api/savePayment';
import type { default as _SaveProgramEp } from '../src/api/saveProgram';
import type { default as _SaveProgramMembersEp } from '../src/api/saveProgramMembers';
import type { default as _SaveReviewEp } from '../src/api/saveReview';
import type { default as _SaveRubricEp } from '../src/api/saveRubric';
import type { default as _SaveSettingsEp } from '../src/api/saveSettings';
import type { default as _SaveStageEp } from '../src/api/saveStage';
import type { default as _SaveTaskEp } from '../src/api/saveTask';
import type { default as _SaveTemplateEp } from '../src/api/saveTemplate';
import type { default as _SaveViewEp } from '../src/api/saveView';
import type { default as _SearchEp } from '../src/api/search';
import type { default as _SeedWorkspaceEp } from '../src/api/seedWorkspace';
import type { default as _SendMessageEp } from '../src/api/sendMessage';
import type { default as _SendRemindersEp } from '../src/api/sendReminders';
import type { default as _SendTestEmailEp } from '../src/api/sendTestEmail';
import type { default as _SetSubmissionLabelsEp } from '../src/api/setSubmissionLabels';
import type { default as _UpdateNoteEp } from '../src/api/updateNote';
import type { default as _UpdateNotificationsEp } from '../src/api/updateNotifications';
import type { default as _UpdateSubmissionEp } from '../src/api/updateSubmission';

type _AddNoteCfg = typeof _AddNoteEp;
export type AddNoteInputType = NonNullable<_AddNoteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AddNoteCfg['execute']>[0]['input'];
export type AddNoteOutputType = Awaited<ReturnType<_AddNoteCfg['execute']>>;
export const addNote = createCaller<AddNoteInputType, AddNoteOutputType>('addNote');

type _AiDraftApplicantFeedbackCfg = typeof _AiDraftApplicantFeedbackEp;
export type AiDraftApplicantFeedbackInputType = NonNullable<_AiDraftApplicantFeedbackCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiDraftApplicantFeedbackCfg['execute']>[0]['input'];
export type AiDraftApplicantFeedbackOutputType = Awaited<ReturnType<_AiDraftApplicantFeedbackCfg['execute']>>;
export const aiDraftApplicantFeedback = createCaller<AiDraftApplicantFeedbackInputType, AiDraftApplicantFeedbackOutputType>('aiDraftApplicantFeedback');

type _AiGenerateFormCfg = typeof _AiGenerateFormEp;
export type AiGenerateFormInputType = NonNullable<_AiGenerateFormCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiGenerateFormCfg['execute']>[0]['input'];
export type AiGenerateFormOutputType = Awaited<ReturnType<_AiGenerateFormCfg['execute']>>;
export const aiGenerateForm = createCaller<AiGenerateFormInputType, AiGenerateFormOutputType>('aiGenerateForm');

type _AiSummarizeSubmissionCfg = typeof _AiSummarizeSubmissionEp;
export type AiSummarizeSubmissionInputType = NonNullable<_AiSummarizeSubmissionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiSummarizeSubmissionCfg['execute']>[0]['input'];
export type AiSummarizeSubmissionOutputType = Awaited<ReturnType<_AiSummarizeSubmissionCfg['execute']>>;
export const aiSummarizeSubmission = createCaller<AiSummarizeSubmissionInputType, AiSummarizeSubmissionOutputType>('aiSummarizeSubmission');

type _AiSynthesizeReviewsCfg = typeof _AiSynthesizeReviewsEp;
export type AiSynthesizeReviewsInputType = NonNullable<_AiSynthesizeReviewsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiSynthesizeReviewsCfg['execute']>[0]['input'];
export type AiSynthesizeReviewsOutputType = Awaited<ReturnType<_AiSynthesizeReviewsCfg['execute']>>;
export const aiSynthesizeReviews = createCaller<AiSynthesizeReviewsInputType, AiSynthesizeReviewsOutputType>('aiSynthesizeReviews');

type _AssignReviewersCfg = typeof _AssignReviewersEp;
export type AssignReviewersInputType = NonNullable<_AssignReviewersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AssignReviewersCfg['execute']>[0]['input'];
export type AssignReviewersOutputType = Awaited<ReturnType<_AssignReviewersCfg['execute']>>;
export const assignReviewers = createCaller<AssignReviewersInputType, AssignReviewersOutputType>('assignReviewers');

type _BootstrapCfg = typeof _BootstrapEp;
export type BootstrapInputType = NonNullable<_BootstrapCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BootstrapCfg['execute']>[0]['input'];
export type BootstrapOutputType = Awaited<ReturnType<_BootstrapCfg['execute']>>;
export const bootstrap = createCaller<BootstrapInputType, BootstrapOutputType>('bootstrap');

type _BulkUpdateSubmissionsCfg = typeof _BulkUpdateSubmissionsEp;
export type BulkUpdateSubmissionsInputType = NonNullable<_BulkUpdateSubmissionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BulkUpdateSubmissionsCfg['execute']>[0]['input'];
export type BulkUpdateSubmissionsOutputType = Awaited<ReturnType<_BulkUpdateSubmissionsCfg['execute']>>;
export const bulkUpdateSubmissions = createCaller<BulkUpdateSubmissionsInputType, BulkUpdateSubmissionsOutputType>('bulkUpdateSubmissions');

type _ClearDemoDataCfg = typeof _ClearDemoDataEp;
export type ClearDemoDataInputType = NonNullable<_ClearDemoDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ClearDemoDataCfg['execute']>[0]['input'];
export type ClearDemoDataOutputType = Awaited<ReturnType<_ClearDemoDataCfg['execute']>>;
export const clearDemoData = createCaller<ClearDemoDataInputType, ClearDemoDataOutputType>('clearDemoData');

type _CreateSubmissionCfg = typeof _CreateSubmissionEp;
export type CreateSubmissionInputType = NonNullable<_CreateSubmissionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateSubmissionCfg['execute']>[0]['input'];
export type CreateSubmissionOutputType = Awaited<ReturnType<_CreateSubmissionCfg['execute']>>;
export const createSubmission = createCaller<CreateSubmissionInputType, CreateSubmissionOutputType>('createSubmission');

type _DecideSubmissionsCfg = typeof _DecideSubmissionsEp;
export type DecideSubmissionsInputType = NonNullable<_DecideSubmissionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DecideSubmissionsCfg['execute']>[0]['input'];
export type DecideSubmissionsOutputType = Awaited<ReturnType<_DecideSubmissionsCfg['execute']>>;
export const decideSubmissions = createCaller<DecideSubmissionsInputType, DecideSubmissionsOutputType>('decideSubmissions');

type _DeleteSubmissionsCfg = typeof _DeleteSubmissionsEp;
export type DeleteSubmissionsInputType = NonNullable<_DeleteSubmissionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteSubmissionsCfg['execute']>[0]['input'];
export type DeleteSubmissionsOutputType = Awaited<ReturnType<_DeleteSubmissionsCfg['execute']>>;
export const deleteSubmissions = createCaller<DeleteSubmissionsInputType, DeleteSubmissionsOutputType>('deleteSubmissions');

type _ExportSubmissionPdfCfg = typeof _ExportSubmissionPdfEp;
export type ExportSubmissionPdfInputType = NonNullable<_ExportSubmissionPdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ExportSubmissionPdfCfg['execute']>[0]['input'];
export type ExportSubmissionPdfOutputType = Awaited<ReturnType<_ExportSubmissionPdfCfg['execute']>>;
export const exportSubmissionPdf = createCaller<ExportSubmissionPdfInputType, ExportSubmissionPdfOutputType>('exportSubmissionPdf');

type _ExportSubmissionsCfg = typeof _ExportSubmissionsEp;
export type ExportSubmissionsInputType = NonNullable<_ExportSubmissionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ExportSubmissionsCfg['execute']>[0]['input'];
export type ExportSubmissionsOutputType = Awaited<ReturnType<_ExportSubmissionsCfg['execute']>>;
export const exportSubmissions = createCaller<ExportSubmissionsInputType, ExportSubmissionsOutputType>('exportSubmissions');

type _GetApplicantCfg = typeof _GetApplicantEp;
export type GetApplicantInputType = NonNullable<_GetApplicantCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetApplicantCfg['execute']>[0]['input'];
export type GetApplicantOutputType = Awaited<ReturnType<_GetApplicantCfg['execute']>>;
export const getApplicant = createCaller<GetApplicantInputType, GetApplicantOutputType>('getApplicant');

type _GetFormCfg = typeof _GetFormEp;
export type GetFormInputType = NonNullable<_GetFormCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetFormCfg['execute']>[0]['input'];
export type GetFormOutputType = Awaited<ReturnType<_GetFormCfg['execute']>>;
export const getForm = createCaller<GetFormInputType, GetFormOutputType>('getForm');

type _GetProgramOverviewCfg = typeof _GetProgramOverviewEp;
export type GetProgramOverviewInputType = NonNullable<_GetProgramOverviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetProgramOverviewCfg['execute']>[0]['input'];
export type GetProgramOverviewOutputType = Awaited<ReturnType<_GetProgramOverviewCfg['execute']>>;
export const getProgramOverview = createCaller<GetProgramOverviewInputType, GetProgramOverviewOutputType>('getProgramOverview');

type _GetReportsCfg = typeof _GetReportsEp;
export type GetReportsInputType = NonNullable<_GetReportsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetReportsCfg['execute']>[0]['input'];
export type GetReportsOutputType = Awaited<ReturnType<_GetReportsCfg['execute']>>;
export const getReports = createCaller<GetReportsInputType, GetReportsOutputType>('getReports');

type _GetReviewCfg = typeof _GetReviewEp;
export type GetReviewInputType = NonNullable<_GetReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetReviewCfg['execute']>[0]['input'];
export type GetReviewOutputType = Awaited<ReturnType<_GetReviewCfg['execute']>>;
export const getReview = createCaller<GetReviewInputType, GetReviewOutputType>('getReview');

type _GetReviewProgressCfg = typeof _GetReviewProgressEp;
export type GetReviewProgressInputType = NonNullable<_GetReviewProgressCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetReviewProgressCfg['execute']>[0]['input'];
export type GetReviewProgressOutputType = Awaited<ReturnType<_GetReviewProgressCfg['execute']>>;
export const getReviewProgress = createCaller<GetReviewProgressInputType, GetReviewProgressOutputType>('getReviewProgress');

type _GetSubmissionCfg = typeof _GetSubmissionEp;
export type GetSubmissionInputType = NonNullable<_GetSubmissionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSubmissionCfg['execute']>[0]['input'];
export type GetSubmissionOutputType = Awaited<ReturnType<_GetSubmissionCfg['execute']>>;
export const getSubmission = createCaller<GetSubmissionInputType, GetSubmissionOutputType>('getSubmission');

type _ListApplicantsCfg = typeof _ListApplicantsEp;
export type ListApplicantsInputType = NonNullable<_ListApplicantsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListApplicantsCfg['execute']>[0]['input'];
export type ListApplicantsOutputType = Awaited<ReturnType<_ListApplicantsCfg['execute']>>;
export const listApplicants = createCaller<ListApplicantsInputType, ListApplicantsOutputType>('listApplicants');

type _ListAwardsCfg = typeof _ListAwardsEp;
export type ListAwardsInputType = NonNullable<_ListAwardsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListAwardsCfg['execute']>[0]['input'];
export type ListAwardsOutputType = Awaited<ReturnType<_ListAwardsCfg['execute']>>;
export const listAwards = createCaller<ListAwardsInputType, ListAwardsOutputType>('listAwards');

type _ListLabelsCfg = typeof _ListLabelsEp;
export type ListLabelsInputType = NonNullable<_ListLabelsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListLabelsCfg['execute']>[0]['input'];
export type ListLabelsOutputType = Awaited<ReturnType<_ListLabelsCfg['execute']>>;
export const listLabels = createCaller<ListLabelsInputType, ListLabelsOutputType>('listLabels');

type _ListMyReviewsCfg = typeof _ListMyReviewsEp;
export type ListMyReviewsInputType = NonNullable<_ListMyReviewsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListMyReviewsCfg['execute']>[0]['input'];
export type ListMyReviewsOutputType = Awaited<ReturnType<_ListMyReviewsCfg['execute']>>;
export const listMyReviews = createCaller<ListMyReviewsInputType, ListMyReviewsOutputType>('listMyReviews');

type _ListNotificationsCfg = typeof _ListNotificationsEp;
export type ListNotificationsInputType = NonNullable<_ListNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListNotificationsCfg['execute']>[0]['input'];
export type ListNotificationsOutputType = Awaited<ReturnType<_ListNotificationsCfg['execute']>>;
export const listNotifications = createCaller<ListNotificationsInputType, ListNotificationsOutputType>('listNotifications');

type _ListPaymentsCfg = typeof _ListPaymentsEp;
export type ListPaymentsInputType = NonNullable<_ListPaymentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPaymentsCfg['execute']>[0]['input'];
export type ListPaymentsOutputType = Awaited<ReturnType<_ListPaymentsCfg['execute']>>;
export const listPayments = createCaller<ListPaymentsInputType, ListPaymentsOutputType>('listPayments');

type _ListProgramStatsCfg = typeof _ListProgramStatsEp;
export type ListProgramStatsInputType = NonNullable<_ListProgramStatsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListProgramStatsCfg['execute']>[0]['input'];
export type ListProgramStatsOutputType = Awaited<ReturnType<_ListProgramStatsCfg['execute']>>;
export const listProgramStats = createCaller<ListProgramStatsInputType, ListProgramStatsOutputType>('listProgramStats');

type _ListSubmissionsCfg = typeof _ListSubmissionsEp;
export type ListSubmissionsInputType = NonNullable<_ListSubmissionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListSubmissionsCfg['execute']>[0]['input'];
export type ListSubmissionsOutputType = Awaited<ReturnType<_ListSubmissionsCfg['execute']>>;
export const listSubmissions = createCaller<ListSubmissionsInputType, ListSubmissionsOutputType>('listSubmissions');

type _ManageReviewCfg = typeof _ManageReviewEp;
export type ManageReviewInputType = NonNullable<_ManageReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ManageReviewCfg['execute']>[0]['input'];
export type ManageReviewOutputType = Awaited<ReturnType<_ManageReviewCfg['execute']>>;
export const manageReview = createCaller<ManageReviewInputType, ManageReviewOutputType>('manageReview');

type _MarkMessagesReadCfg = typeof _MarkMessagesReadEp;
export type MarkMessagesReadInputType = NonNullable<_MarkMessagesReadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MarkMessagesReadCfg['execute']>[0]['input'];
export type MarkMessagesReadOutputType = Awaited<ReturnType<_MarkMessagesReadCfg['execute']>>;
export const markMessagesRead = createCaller<MarkMessagesReadInputType, MarkMessagesReadOutputType>('markMessagesRead');

type _SaveApplicantCfg = typeof _SaveApplicantEp;
export type SaveApplicantInputType = NonNullable<_SaveApplicantCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveApplicantCfg['execute']>[0]['input'];
export type SaveApplicantOutputType = Awaited<ReturnType<_SaveApplicantCfg['execute']>>;
export const saveApplicant = createCaller<SaveApplicantInputType, SaveApplicantOutputType>('saveApplicant');

type _SaveAttachmentCfg = typeof _SaveAttachmentEp;
export type SaveAttachmentInputType = NonNullable<_SaveAttachmentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveAttachmentCfg['execute']>[0]['input'];
export type SaveAttachmentOutputType = Awaited<ReturnType<_SaveAttachmentCfg['execute']>>;
export const saveAttachment = createCaller<SaveAttachmentInputType, SaveAttachmentOutputType>('saveAttachment');

type _SaveFormCfg = typeof _SaveFormEp;
export type SaveFormInputType = NonNullable<_SaveFormCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveFormCfg['execute']>[0]['input'];
export type SaveFormOutputType = Awaited<ReturnType<_SaveFormCfg['execute']>>;
export const saveForm = createCaller<SaveFormInputType, SaveFormOutputType>('saveForm');

type _SaveLabelCfg = typeof _SaveLabelEp;
export type SaveLabelInputType = NonNullable<_SaveLabelCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveLabelCfg['execute']>[0]['input'];
export type SaveLabelOutputType = Awaited<ReturnType<_SaveLabelCfg['execute']>>;
export const saveLabel = createCaller<SaveLabelInputType, SaveLabelOutputType>('saveLabel');

type _SaveMemberCfg = typeof _SaveMemberEp;
export type SaveMemberInputType = NonNullable<_SaveMemberCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveMemberCfg['execute']>[0]['input'];
export type SaveMemberOutputType = Awaited<ReturnType<_SaveMemberCfg['execute']>>;
export const saveMember = createCaller<SaveMemberInputType, SaveMemberOutputType>('saveMember');

type _SavePaymentCfg = typeof _SavePaymentEp;
export type SavePaymentInputType = NonNullable<_SavePaymentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SavePaymentCfg['execute']>[0]['input'];
export type SavePaymentOutputType = Awaited<ReturnType<_SavePaymentCfg['execute']>>;
export const savePayment = createCaller<SavePaymentInputType, SavePaymentOutputType>('savePayment');

type _SaveProgramCfg = typeof _SaveProgramEp;
export type SaveProgramInputType = NonNullable<_SaveProgramCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveProgramCfg['execute']>[0]['input'];
export type SaveProgramOutputType = Awaited<ReturnType<_SaveProgramCfg['execute']>>;
export const saveProgram = createCaller<SaveProgramInputType, SaveProgramOutputType>('saveProgram');

type _SaveProgramMembersCfg = typeof _SaveProgramMembersEp;
export type SaveProgramMembersInputType = NonNullable<_SaveProgramMembersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveProgramMembersCfg['execute']>[0]['input'];
export type SaveProgramMembersOutputType = Awaited<ReturnType<_SaveProgramMembersCfg['execute']>>;
export const saveProgramMembers = createCaller<SaveProgramMembersInputType, SaveProgramMembersOutputType>('saveProgramMembers');

type _SaveReviewCfg = typeof _SaveReviewEp;
export type SaveReviewInputType = NonNullable<_SaveReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveReviewCfg['execute']>[0]['input'];
export type SaveReviewOutputType = Awaited<ReturnType<_SaveReviewCfg['execute']>>;
export const saveReview = createCaller<SaveReviewInputType, SaveReviewOutputType>('saveReview');

type _SaveRubricCfg = typeof _SaveRubricEp;
export type SaveRubricInputType = NonNullable<_SaveRubricCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveRubricCfg['execute']>[0]['input'];
export type SaveRubricOutputType = Awaited<ReturnType<_SaveRubricCfg['execute']>>;
export const saveRubric = createCaller<SaveRubricInputType, SaveRubricOutputType>('saveRubric');

type _SaveSettingsCfg = typeof _SaveSettingsEp;
export type SaveSettingsInputType = NonNullable<_SaveSettingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveSettingsCfg['execute']>[0]['input'];
export type SaveSettingsOutputType = Awaited<ReturnType<_SaveSettingsCfg['execute']>>;
export const saveSettings = createCaller<SaveSettingsInputType, SaveSettingsOutputType>('saveSettings');

type _SaveStageCfg = typeof _SaveStageEp;
export type SaveStageInputType = NonNullable<_SaveStageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveStageCfg['execute']>[0]['input'];
export type SaveStageOutputType = Awaited<ReturnType<_SaveStageCfg['execute']>>;
export const saveStage = createCaller<SaveStageInputType, SaveStageOutputType>('saveStage');

type _SaveTaskCfg = typeof _SaveTaskEp;
export type SaveTaskInputType = NonNullable<_SaveTaskCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTaskCfg['execute']>[0]['input'];
export type SaveTaskOutputType = Awaited<ReturnType<_SaveTaskCfg['execute']>>;
export const saveTask = createCaller<SaveTaskInputType, SaveTaskOutputType>('saveTask');

type _SaveTemplateCfg = typeof _SaveTemplateEp;
export type SaveTemplateInputType = NonNullable<_SaveTemplateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTemplateCfg['execute']>[0]['input'];
export type SaveTemplateOutputType = Awaited<ReturnType<_SaveTemplateCfg['execute']>>;
export const saveTemplate = createCaller<SaveTemplateInputType, SaveTemplateOutputType>('saveTemplate');

type _SaveViewCfg = typeof _SaveViewEp;
export type SaveViewInputType = NonNullable<_SaveViewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveViewCfg['execute']>[0]['input'];
export type SaveViewOutputType = Awaited<ReturnType<_SaveViewCfg['execute']>>;
export const saveView = createCaller<SaveViewInputType, SaveViewOutputType>('saveView');

type _SearchCfg = typeof _SearchEp;
export type SearchInputType = NonNullable<_SearchCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SearchCfg['execute']>[0]['input'];
export type SearchOutputType = Awaited<ReturnType<_SearchCfg['execute']>>;
export const search = createCaller<SearchInputType, SearchOutputType>('search');

type _SeedWorkspaceCfg = typeof _SeedWorkspaceEp;
export type SeedWorkspaceInputType = NonNullable<_SeedWorkspaceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SeedWorkspaceCfg['execute']>[0]['input'];
export type SeedWorkspaceOutputType = Awaited<ReturnType<_SeedWorkspaceCfg['execute']>>;
export const seedWorkspace = createCaller<SeedWorkspaceInputType, SeedWorkspaceOutputType>('seedWorkspace');

type _SendMessageCfg = typeof _SendMessageEp;
export type SendMessageInputType = NonNullable<_SendMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendMessageCfg['execute']>[0]['input'];
export type SendMessageOutputType = Awaited<ReturnType<_SendMessageCfg['execute']>>;
export const sendMessage = createCaller<SendMessageInputType, SendMessageOutputType>('sendMessage');

type _SendRemindersCfg = typeof _SendRemindersEp;
export type SendRemindersInputType = NonNullable<_SendRemindersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendRemindersCfg['execute']>[0]['input'];
export type SendRemindersOutputType = Awaited<ReturnType<_SendRemindersCfg['execute']>>;
export const sendReminders = createCaller<SendRemindersInputType, SendRemindersOutputType>('sendReminders');

type _SendTestEmailCfg = typeof _SendTestEmailEp;
export type SendTestEmailInputType = NonNullable<_SendTestEmailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendTestEmailCfg['execute']>[0]['input'];
export type SendTestEmailOutputType = Awaited<ReturnType<_SendTestEmailCfg['execute']>>;
export const sendTestEmail = createCaller<SendTestEmailInputType, SendTestEmailOutputType>('sendTestEmail');

type _SetSubmissionLabelsCfg = typeof _SetSubmissionLabelsEp;
export type SetSubmissionLabelsInputType = NonNullable<_SetSubmissionLabelsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetSubmissionLabelsCfg['execute']>[0]['input'];
export type SetSubmissionLabelsOutputType = Awaited<ReturnType<_SetSubmissionLabelsCfg['execute']>>;
export const setSubmissionLabels = createCaller<SetSubmissionLabelsInputType, SetSubmissionLabelsOutputType>('setSubmissionLabels');

type _UpdateNoteCfg = typeof _UpdateNoteEp;
export type UpdateNoteInputType = NonNullable<_UpdateNoteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateNoteCfg['execute']>[0]['input'];
export type UpdateNoteOutputType = Awaited<ReturnType<_UpdateNoteCfg['execute']>>;
export const updateNote = createCaller<UpdateNoteInputType, UpdateNoteOutputType>('updateNote');

type _UpdateNotificationsCfg = typeof _UpdateNotificationsEp;
export type UpdateNotificationsInputType = NonNullable<_UpdateNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateNotificationsCfg['execute']>[0]['input'];
export type UpdateNotificationsOutputType = Awaited<ReturnType<_UpdateNotificationsCfg['execute']>>;
export const updateNotifications = createCaller<UpdateNotificationsInputType, UpdateNotificationsOutputType>('updateNotifications');

type _UpdateSubmissionCfg = typeof _UpdateSubmissionEp;
export type UpdateSubmissionInputType = NonNullable<_UpdateSubmissionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateSubmissionCfg['execute']>[0]['input'];
export type UpdateSubmissionOutputType = Awaited<ReturnType<_UpdateSubmissionCfg['execute']>>;
export const updateSubmission = createCaller<UpdateSubmissionInputType, UpdateSubmissionOutputType>('updateSubmission');


export const api = {
  addNote,
  aiDraftApplicantFeedback,
  aiGenerateForm,
  aiSummarizeSubmission,
  aiSynthesizeReviews,
  assignReviewers,
  bootstrap,
  bulkUpdateSubmissions,
  clearDemoData,
  createSubmission,
  decideSubmissions,
  deleteSubmissions,
  exportSubmissionPdf,
  exportSubmissions,
  getApplicant,
  getForm,
  getProgramOverview,
  getReports,
  getReview,
  getReviewProgress,
  getSubmission,
  listApplicants,
  listAwards,
  listLabels,
  listMyReviews,
  listNotifications,
  listPayments,
  listProgramStats,
  listSubmissions,
  manageReview,
  markMessagesRead,
  saveApplicant,
  saveAttachment,
  saveForm,
  saveLabel,
  saveMember,
  savePayment,
  saveProgram,
  saveProgramMembers,
  saveReview,
  saveRubric,
  saveSettings,
  saveStage,
  saveTask,
  saveTemplate,
  saveView,
  search,
  seedWorkspace,
  sendMessage,
  sendReminders,
  sendTestEmail,
  setSubmissionLabels,
  updateNote,
  updateNotifications,
  updateSubmission,
};
