// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//     a filter value of `undefined` is REJECTED (it would query unfiltered
//       and match an arbitrary record). Check the value first.
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Settings" table, as it is read back. */
export type SettingsRecordType = {
  id: string;
  /** Primary field. "Organization Name" */
  organizationName?: string;
  logoUrl?: string;
  websiteUrl?: string;
  supportEmail?: string;
  brandColor?: string;
  currency?: string;
  portalHeadline?: string;
  portalIntro?: string;
  emailSignature?: string;
  privacyUrl?: string;
  defaultRole?: "Manager" | "Reviewer" | string;
  /** "Seeded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  seededAt?: string;
  portalUrl?: string;
  staffAppUrl?: string;
};

/** What you may write when creating or updating a record in the "Settings" table. */
export type SettingsRecordInput = {
  organizationName: string | null;
  logoUrl: string | null;
  websiteUrl: string | null;
  supportEmail: string | null;
  brandColor: string | null;
  currency: string | null;
  portalHeadline: string | null;
  portalIntro: string | null;
  emailSignature: string | null;
  privacyUrl: string | null;
  defaultRole: "Manager" | "Reviewer" | string | null;
  seededAt: string | Date | null;
  portalUrl: string | null;
  staffAppUrl: string | null;
};

/** A record in the "Members" table, as it is read back. */
export type MembersRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  email?: string;
  role?: "Admin" | "Manager" | "Reviewer" | string;
  status?: "Active" | "Invited" | "Deactivated" | string;
  color?: string;
  avatarUrl?: string;
  title?: string;
  expertise?: string;
  /** "Invited At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  invitedAt?: string;
  /** "Last Seen At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastSeenAt?: string;
};

/** What you may write when creating or updating a record in the "Members" table. */
export type MembersRecordInput = {
  name: string | null;
  email: string | null;
  role: "Admin" | "Manager" | "Reviewer" | string | null;
  status: "Active" | "Invited" | "Deactivated" | string | null;
  color: string | null;
  avatarUrl: string | null;
  title: string | null;
  expertise: string | null;
  invitedAt: string | Date | null;
  lastSeenAt: string | Date | null;
};

/** A record in the "Programs" table, as it is read back. */
export type ProgramsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  key?: string;
  slug?: string;
  type?: "Grant" | "Scholarship" | "Fellowship" | "Award" | "Residency" | "Open call" | "Other" | string;
  status?: "Draft" | "Published" | "Archived" | string;
  summary?: string;
  description?: string;
  eligibility?: string;
  /** "Opens At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  opensAt?: string;
  /** "Deadline". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  deadline?: string;
  allowLate?: boolean;
  /** "Budget". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  budget?: number;
  /** "Award Min". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  awardMin?: number;
  /** "Award Max". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  awardMax?: number;
  color?: string;
  icon?: string;
  coverImageUrl?: string;
  ownerId?: string;
  blindReview?: boolean;
  /** "Reviewers Per Submission". 0 decimal places, format: local (e.g. 1,000,000.50) */
  reviewersPerSubmission?: number;
  showScoresToReviewers?: boolean;
  /** "Max Per Applicant". 0 decimal places, format: local (e.g. 1,000,000.50) */
  maxPerApplicant?: number;
  confirmationMessage?: string;
  contactEmail?: string;
  /** "Submission Counter". 0 decimal places, format: local (e.g. 1,000,000.50) */
  submissionCounter?: number;
  /** "Position". 2 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  /** "Published At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  publishedAt?: string;
};

/** What you may write when creating or updating a record in the "Programs" table. */
export type ProgramsRecordInput = {
  name: string | null;
  key: string | null;
  slug: string | null;
  type: "Grant" | "Scholarship" | "Fellowship" | "Award" | "Residency" | "Open call" | "Other" | string | null;
  status: "Draft" | "Published" | "Archived" | string | null;
  summary: string | null;
  description: string | null;
  eligibility: string | null;
  opensAt: string | Date | null;
  deadline: string | Date | null;
  allowLate: string | boolean | null;
  budget: string | number | null;
  awardMin: string | number | null;
  awardMax: string | number | null;
  color: string | null;
  icon: string | null;
  coverImageUrl: string | null;
  ownerId: string | null;
  blindReview: string | boolean | null;
  reviewersPerSubmission: string | number | null;
  showScoresToReviewers: string | boolean | null;
  maxPerApplicant: string | number | null;
  confirmationMessage: string | null;
  contactEmail: string | null;
  submissionCounter: string | number | null;
  position: string | number | null;
  publishedAt: string | Date | null;
};

/** A record in the "Program Members" table, as it is read back. */
export type ProgramMembersRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  programId?: string;
  memberId?: string;
  role?: "Manager" | "Reviewer" | string;
};

/** What you may write when creating or updating a record in the "Program Members" table. */
export type ProgramMembersRecordInput = {
  name: string | null;
  programId: string | null;
  memberId: string | null;
  role: "Manager" | "Reviewer" | string | null;
};

/** A record in the "Forms" table, as it is read back. */
export type FormsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  programId?: string;
  kind?: "Application" | "Follow-up" | string;
  description?: string;
  fields?: string;
  titleFieldId?: string;
  amountFieldId?: string;
  /** "Position". 2 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Forms" table. */
export type FormsRecordInput = {
  name: string | null;
  programId: string | null;
  kind: "Application" | "Follow-up" | string | null;
  description: string | null;
  fields: string | null;
  titleFieldId: string | null;
  amountFieldId: string | null;
  position: string | number | null;
};

/** A record in the "Stages" table, as it is read back. */
export type StagesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  programId?: string;
  kind?: "Intake" | "Review" | "Decision" | string;
  /** "Position". 2 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  color?: string;
  rubricId?: string;
  description?: string;
};

/** What you may write when creating or updating a record in the "Stages" table. */
export type StagesRecordInput = {
  name: string | null;
  programId: string | null;
  kind: "Intake" | "Review" | "Decision" | string | null;
  position: string | number | null;
  color: string | null;
  rubricId: string | null;
  description: string | null;
};

/** A record in the "Rubrics" table, as it is read back. */
export type RubricsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  programId?: string;
  instructions?: string;
  criteria?: string;
  askRecommendation?: boolean;
};

/** What you may write when creating or updating a record in the "Rubrics" table. */
export type RubricsRecordInput = {
  name: string | null;
  programId: string | null;
  instructions: string | null;
  criteria: string | null;
  askRecommendation: string | boolean | null;
};

/** A record in the "Applicants" table, as it is read back. */
export type ApplicantsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  email?: string;
  phone?: string;
  organization?: string;
  location?: string;
  website?: string;
  notes?: string;
  /** "Joined At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  joinedAt?: string;
  /** "Last Active At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastActiveAt?: string;
};

/** What you may write when creating or updating a record in the "Applicants" table. */
export type ApplicantsRecordInput = {
  name: string | null;
  email: string | null;
  phone: string | null;
  organization: string | null;
  location: string | null;
  website: string | null;
  notes: string | null;
  joinedAt: string | Date | null;
  lastActiveAt: string | Date | null;
};

/** A record in the "Submissions" table, as it is read back. */
export type SubmissionsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  /** "Number". 0 decimal places, format: local (e.g. 1,000,000.50) */
  number?: number;
  programId?: string;
  applicantId?: string;
  stageId?: string;
  ownerId?: string;
  status?: "Draft" | "Submitted" | "Accepted" | "Declined" | "Waitlisted" | "Withdrawn" | string;
  answers?: string;
  /** "Requested Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  requestedAmount?: number;
  /** "Award Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  awardAmount?: number;
  awardStatus?: "Pending" | "Active" | "Completed" | "Cancelled" | string;
  /** "Award Start Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  awardStartDate?: string;
  /** "Award End Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  awardEndDate?: string;
  decisionReason?: string;
  decisionNote?: string;
  /** "Started At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  startedAt?: string;
  /** "Last Saved At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastSavedAt?: string;
  /** "Submitted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  submittedAt?: string;
  /** "Stage Entered At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  stageEnteredAt?: string;
  /** "Decided At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  decidedAt?: string;
  decidedById?: string;
  /** "Notified At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  notifiedAt?: string;
  /** "Withdrawn At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  withdrawnAt?: string;
  /** "Last Activity At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastActivityAt?: string;
  /** "Reminded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  remindedAt?: string;
};

/** What you may write when creating or updating a record in the "Submissions" table. */
export type SubmissionsRecordInput = {
  title: string | null;
  number: string | number | null;
  programId: string | null;
  applicantId: string | null;
  stageId: string | null;
  ownerId: string | null;
  status: "Draft" | "Submitted" | "Accepted" | "Declined" | "Waitlisted" | "Withdrawn" | string | null;
  answers: string | null;
  requestedAmount: string | number | null;
  awardAmount: string | number | null;
  awardStatus: "Pending" | "Active" | "Completed" | "Cancelled" | string | null;
  awardStartDate: string | Date | null;
  awardEndDate: string | Date | null;
  decisionReason: string | null;
  decisionNote: string | null;
  startedAt: string | Date | null;
  lastSavedAt: string | Date | null;
  submittedAt: string | Date | null;
  stageEnteredAt: string | Date | null;
  decidedAt: string | Date | null;
  decidedById: string | null;
  notifiedAt: string | Date | null;
  withdrawnAt: string | Date | null;
  lastActivityAt: string | Date | null;
  remindedAt: string | Date | null;
};

/** A record in the "Reviews" table, as it is read back. */
export type ReviewsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  submissionId?: string;
  reviewerId?: string;
  stageId?: string;
  rubricId?: string;
  programId?: string;
  status?: "Assigned" | "In progress" | "Submitted" | "Recused" | string;
  scores?: string;
  /** "Total Score". 1 decimal places, format: local (e.g. 1,000,000.50) */
  totalScore?: number;
  recommendation?: string;
  comment?: string;
  applicantFeedback?: string;
  recusalReason?: string;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  /** "Assigned At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  assignedAt?: string;
  assignedById?: string;
  /** "Started At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  startedAt?: string;
  /** "Submitted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  submittedAt?: string;
  /** "Reminded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  remindedAt?: string;
};

/** What you may write when creating or updating a record in the "Reviews" table. */
export type ReviewsRecordInput = {
  name: string | null;
  submissionId: string | null;
  reviewerId: string | null;
  stageId: string | null;
  rubricId: string | null;
  programId: string | null;
  status: "Assigned" | "In progress" | "Submitted" | "Recused" | string | null;
  scores: string | null;
  totalScore: string | number | null;
  recommendation: string | null;
  comment: string | null;
  applicantFeedback: string | null;
  recusalReason: string | null;
  dueDate: string | Date | null;
  assignedAt: string | Date | null;
  assignedById: string | null;
  startedAt: string | Date | null;
  submittedAt: string | Date | null;
  remindedAt: string | Date | null;
};

/** A record in the "Notes" table, as it is read back. */
export type NotesRecordType = {
  id: string;
  /** Primary field. "Body" */
  body?: string;
  submissionId?: string;
  applicantId?: string;
  authorId?: string;
  /** "Posted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  postedAt?: string;
  /** "Edited At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  editedAt?: string;
};

/** What you may write when creating or updating a record in the "Notes" table. */
export type NotesRecordInput = {
  body: string | null;
  submissionId: string | null;
  applicantId: string | null;
  authorId: string | null;
  postedAt: string | Date | null;
  editedAt: string | Date | null;
};

/** A record in the "Messages" table, as it is read back. */
export type MessagesRecordType = {
  id: string;
  /** Primary field. "Subject" */
  subject?: string;
  body?: string;
  submissionId?: string;
  applicantId?: string;
  senderId?: string;
  direction?: "Outbound" | "Inbound" | string;
  kind?: "Message" | "Confirmation" | "Decision" | "Request" | "Reminder" | string;
  delivery?: "Sent" | "Portal only" | "Failed" | string;
  templateId?: string;
  /** "Sent At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  sentAt?: string;
  /** "Read At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  readAt?: string;
};

/** What you may write when creating or updating a record in the "Messages" table. */
export type MessagesRecordInput = {
  subject: string | null;
  body: string | null;
  submissionId: string | null;
  applicantId: string | null;
  senderId: string | null;
  direction: "Outbound" | "Inbound" | string | null;
  kind: "Message" | "Confirmation" | "Decision" | "Request" | "Reminder" | string | null;
  delivery: "Sent" | "Portal only" | "Failed" | string | null;
  templateId: string | null;
  sentAt: string | Date | null;
  readAt: string | Date | null;
};

/** A record in the "Email Templates" table, as it is read back. */
export type EmailTemplatesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  subject?: string;
  body?: string;
  trigger?: "Manual" | "Submission received" | "Accepted" | "Declined" | "Waitlisted" | "Task requested" | "Draft reminder" | string;
  programId?: string;
  enabled?: boolean;
  /** "Position". 2 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Email Templates" table. */
export type EmailTemplatesRecordInput = {
  name: string | null;
  subject: string | null;
  body: string | null;
  trigger: "Manual" | "Submission received" | "Accepted" | "Declined" | "Waitlisted" | "Task requested" | "Draft reminder" | string | null;
  programId: string | null;
  enabled: string | boolean | null;
  position: string | number | null;
};

/** A record in the "Tasks" table, as it is read back. */
export type TasksRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  submissionId?: string;
  applicantId?: string;
  programId?: string;
  formId?: string;
  instructions?: string;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  status?: "Open" | "Submitted" | "Approved" | "Returned" | string;
  answers?: string;
  requestedById?: string;
  /** "Requested At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  requestedAt?: string;
  /** "Submitted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  submittedAt?: string;
  /** "Reviewed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  reviewedAt?: string;
  reviewedById?: string;
  reviewNote?: string;
  /** "Reminded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  remindedAt?: string;
};

/** What you may write when creating or updating a record in the "Tasks" table. */
export type TasksRecordInput = {
  title: string | null;
  submissionId: string | null;
  applicantId: string | null;
  programId: string | null;
  formId: string | null;
  instructions: string | null;
  dueDate: string | Date | null;
  status: "Open" | "Submitted" | "Approved" | "Returned" | string | null;
  answers: string | null;
  requestedById: string | null;
  requestedAt: string | Date | null;
  submittedAt: string | Date | null;
  reviewedAt: string | Date | null;
  reviewedById: string | null;
  reviewNote: string | null;
  remindedAt: string | Date | null;
};

/** A record in the "Payments" table, as it is read back. */
export type PaymentsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  submissionId?: string;
  programId?: string;
  /** "Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  /** "Paid Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  paidDate?: string;
  status?: "Scheduled" | "Paid" | "On hold" | "Cancelled" | string;
  method?: "ACH" | "Check" | "Wire" | "Card" | "Other" | string;
  reference?: string;
  notes?: string;
  recordedById?: string;
};

/** What you may write when creating or updating a record in the "Payments" table. */
export type PaymentsRecordInput = {
  name: string | null;
  submissionId: string | null;
  programId: string | null;
  amount: string | number | null;
  dueDate: string | Date | null;
  paidDate: string | Date | null;
  status: "Scheduled" | "Paid" | "On hold" | "Cancelled" | string | null;
  method: "ACH" | "Check" | "Wire" | "Card" | "Other" | string | null;
  reference: string | null;
  notes: string | null;
  recordedById: string | null;
};

/** A record in the "Labels" table, as it is read back. */
export type LabelsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  color?: string;
  programId?: string;
  description?: string;
};

/** What you may write when creating or updating a record in the "Labels" table. */
export type LabelsRecordInput = {
  name: string | null;
  color: string | null;
  programId: string | null;
  description: string | null;
};

/** A record in the "Submission Labels" table, as it is read back. */
export type SubmissionLabelsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  submissionId?: string;
  labelId?: string;
};

/** What you may write when creating or updating a record in the "Submission Labels" table. */
export type SubmissionLabelsRecordInput = {
  name: string | null;
  submissionId: string | null;
  labelId: string | null;
};

/** A record in the "Attachments" table, as it is read back. */
export type AttachmentsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  url?: string;
  /** "Size". 0 decimal places, format: local (e.g. 1,000,000.50) */
  size?: number;
  mimeType?: string;
  submissionId?: string;
  uploadedById?: string;
  /** "Uploaded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  uploadedAt?: string;
};

/** What you may write when creating or updating a record in the "Attachments" table. */
export type AttachmentsRecordInput = {
  name: string | null;
  url: string | null;
  size: string | number | null;
  mimeType: string | null;
  submissionId: string | null;
  uploadedById: string | null;
  uploadedAt: string | Date | null;
};

/** A record in the "Activity" table, as it is read back. */
export type ActivityRecordType = {
  id: string;
  /** Primary field. "Type" */
  type?: string;
  submissionId?: string;
  programId?: string;
  applicantId?: string;
  actorId?: string;
  actorType?: "Member" | "Applicant" | "System" | string;
  data?: string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
};

/** What you may write when creating or updating a record in the "Activity" table. */
export type ActivityRecordInput = {
  type: string | null;
  submissionId: string | null;
  programId: string | null;
  applicantId: string | null;
  actorId: string | null;
  actorType: "Member" | "Applicant" | "System" | string | null;
  data: string | null;
  occurredAt: string | Date | null;
};

/** A record in the "Notifications" table, as it is read back. */
export type NotificationsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  body?: string;
  type?: string;
  recipientId?: string;
  actorId?: string;
  actorType?: string;
  submissionId?: string;
  programId?: string;
  link?: string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
  /** "Read At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  readAt?: string;
  /** "Archived At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  archivedAt?: string;
  /** "Snoozed Until". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  snoozedUntil?: string;
};

/** What you may write when creating or updating a record in the "Notifications" table. */
export type NotificationsRecordInput = {
  title: string | null;
  body: string | null;
  type: string | null;
  recipientId: string | null;
  actorId: string | null;
  actorType: string | null;
  submissionId: string | null;
  programId: string | null;
  link: string | null;
  occurredAt: string | Date | null;
  readAt: string | Date | null;
  archivedAt: string | Date | null;
  snoozedUntil: string | Date | null;
};

/** A record in the "Views" table, as it is read back. */
export type ViewsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  ownerId?: string;
  scope?: "Personal" | "Shared" | string;
  programId?: string;
  config?: string;
  /** "Position". 2 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Views" table. */
export type ViewsRecordInput = {
  name: string | null;
  ownerId: string | null;
  scope: "Personal" | "Shared" | string | null;
  programId: string | null;
  config: string | null;
  position: string | number | null;
};

export interface NotificationLink {
  path?: string;
  params?: Record<string, string>;
}

export interface NotificationsCreateParams {
  recipients: string[];
  title: string;
  body?: string;
  link?: NotificationLink;
  path?: string;
  params?: Record<string, string>;
  payload?: Record<string, unknown>;
  idempotencyKey?: string;
}

export type NotificationsCreateResult =
  | { created: number }
  | { created: 0; preview: true; wouldCreate: number };

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  settings: createTableClient<SettingsRecordType, SettingsRecordInput>('Settings'), // "Settings"
  members: createTableClient<MembersRecordType, MembersRecordInput>('Members'), // "Members"
  programs: createTableClient<ProgramsRecordType, ProgramsRecordInput>('Programs'), // "Programs"
  programMembers: createTableClient<ProgramMembersRecordType, ProgramMembersRecordInput>('ProgramMembers'), // "Program Members"
  forms: createTableClient<FormsRecordType, FormsRecordInput>('Forms'), // "Forms"
  stages: createTableClient<StagesRecordType, StagesRecordInput>('Stages'), // "Stages"
  rubrics: createTableClient<RubricsRecordType, RubricsRecordInput>('Rubrics'), // "Rubrics"
  applicants: createTableClient<ApplicantsRecordType, ApplicantsRecordInput>('Applicants'), // "Applicants"
  submissions: createTableClient<SubmissionsRecordType, SubmissionsRecordInput>('Submissions'), // "Submissions"
  reviews: createTableClient<ReviewsRecordType, ReviewsRecordInput>('Reviews'), // "Reviews"
  notes: createTableClient<NotesRecordType, NotesRecordInput>('Notes'), // "Notes"
  messages: createTableClient<MessagesRecordType, MessagesRecordInput>('Messages'), // "Messages"
  emailTemplates: createTableClient<EmailTemplatesRecordType, EmailTemplatesRecordInput>('EmailTemplates'), // "Email Templates"
  tasks: createTableClient<TasksRecordType, TasksRecordInput>('Tasks'), // "Tasks"
  payments: createTableClient<PaymentsRecordType, PaymentsRecordInput>('Payments'), // "Payments"
  labels: createTableClient<LabelsRecordType, LabelsRecordInput>('Labels'), // "Labels"
  submissionLabels: createTableClient<SubmissionLabelsRecordType, SubmissionLabelsRecordInput>('SubmissionLabels'), // "Submission Labels"
  attachments: createTableClient<AttachmentsRecordType, AttachmentsRecordInput>('Attachments'), // "Attachments"
  activity: createTableClient<ActivityRecordType, ActivityRecordInput>('Activity'), // "Activity"
  notifications: createTableClient<NotificationsRecordType, NotificationsRecordInput>('Notifications'), // "Notifications"
  views: createTableClient<ViewsRecordType, ViewsRecordInput>('Views'), // "Views"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
